################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/api_lib.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/api_msg.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/err.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/netbuf.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/netdb.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/netifapi.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/sockets.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/tcpip.c 

OBJS += \
./src/network/lwip2.0.3/api/api_lib.o \
./src/network/lwip2.0.3/api/api_msg.o \
./src/network/lwip2.0.3/api/err.o \
./src/network/lwip2.0.3/api/netbuf.o \
./src/network/lwip2.0.3/api/netdb.o \
./src/network/lwip2.0.3/api/netifapi.o \
./src/network/lwip2.0.3/api/sockets.o \
./src/network/lwip2.0.3/api/tcpip.o 

C_DEPS += \
./src/network/lwip2.0.3/api/api_lib.d \
./src/network/lwip2.0.3/api/api_msg.d \
./src/network/lwip2.0.3/api/err.d \
./src/network/lwip2.0.3/api/netbuf.d \
./src/network/lwip2.0.3/api/netdb.d \
./src/network/lwip2.0.3/api/netifapi.d \
./src/network/lwip2.0.3/api/sockets.d \
./src/network/lwip2.0.3/api/tcpip.d 


# Each subdirectory must supply rules for building sources it contributes
src/network/lwip2.0.3/api/api_lib.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/api_lib.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_driver -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/arch/xt804/libs -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/drivers/psram -I../../../../../../../platform/sys -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -I../../../../../../../src/app/fatfs -Os -fdata-sections -mhard-float -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/network/lwip2.0.3/api/api_msg.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/api_msg.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_driver -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/arch/xt804/libs -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/drivers/psram -I../../../../../../../platform/sys -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -I../../../../../../../src/app/fatfs -Os -fdata-sections -mhard-float -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/network/lwip2.0.3/api/err.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/err.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_driver -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/arch/xt804/libs -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/drivers/psram -I../../../../../../../platform/sys -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -I../../../../../../../src/app/fatfs -Os -fdata-sections -mhard-float -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/network/lwip2.0.3/api/netbuf.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/netbuf.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_driver -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/arch/xt804/libs -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/drivers/psram -I../../../../../../../platform/sys -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -I../../../../../../../src/app/fatfs -Os -fdata-sections -mhard-float -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/network/lwip2.0.3/api/netdb.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/netdb.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_driver -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/arch/xt804/libs -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/drivers/psram -I../../../../../../../platform/sys -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -I../../../../../../../src/app/fatfs -Os -fdata-sections -mhard-float -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/network/lwip2.0.3/api/netifapi.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/netifapi.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_driver -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/arch/xt804/libs -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/drivers/psram -I../../../../../../../platform/sys -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -I../../../../../../../src/app/fatfs -Os -fdata-sections -mhard-float -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/network/lwip2.0.3/api/sockets.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/sockets.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_driver -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/arch/xt804/libs -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/drivers/psram -I../../../../../../../platform/sys -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -I../../../../../../../src/app/fatfs -Os -fdata-sections -mhard-float -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/network/lwip2.0.3/api/tcpip.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/network/lwip2.0.3/api/tcpip.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_driver -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/arch/xt804/libs -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/drivers/psram -I../../../../../../../platform/sys -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -I../../../../../../../src/app/fatfs -Os -fdata-sections -mhard-float -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"

