################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/base64-decode.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/client-handshake.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/client-parser.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/client.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/context.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/handshake.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/header.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/libwebsockets.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/lws-plat-wm.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/output.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/parsers.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/pollfd.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/service.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/ssl-client.c \
D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/ssl.c 

OBJS += \
./src/app/libwebsockets-2.1-stable/base64-decode.o \
./src/app/libwebsockets-2.1-stable/client-handshake.o \
./src/app/libwebsockets-2.1-stable/client-parser.o \
./src/app/libwebsockets-2.1-stable/client.o \
./src/app/libwebsockets-2.1-stable/context.o \
./src/app/libwebsockets-2.1-stable/handshake.o \
./src/app/libwebsockets-2.1-stable/header.o \
./src/app/libwebsockets-2.1-stable/libwebsockets.o \
./src/app/libwebsockets-2.1-stable/lws-plat-wm.o \
./src/app/libwebsockets-2.1-stable/output.o \
./src/app/libwebsockets-2.1-stable/parsers.o \
./src/app/libwebsockets-2.1-stable/pollfd.o \
./src/app/libwebsockets-2.1-stable/service.o \
./src/app/libwebsockets-2.1-stable/ssl-client.o \
./src/app/libwebsockets-2.1-stable/ssl.o 

C_DEPS += \
./src/app/libwebsockets-2.1-stable/base64-decode.d \
./src/app/libwebsockets-2.1-stable/client-handshake.d \
./src/app/libwebsockets-2.1-stable/client-parser.d \
./src/app/libwebsockets-2.1-stable/client.d \
./src/app/libwebsockets-2.1-stable/context.d \
./src/app/libwebsockets-2.1-stable/handshake.d \
./src/app/libwebsockets-2.1-stable/header.d \
./src/app/libwebsockets-2.1-stable/libwebsockets.d \
./src/app/libwebsockets-2.1-stable/lws-plat-wm.d \
./src/app/libwebsockets-2.1-stable/output.d \
./src/app/libwebsockets-2.1-stable/parsers.d \
./src/app/libwebsockets-2.1-stable/pollfd.d \
./src/app/libwebsockets-2.1-stable/service.d \
./src/app/libwebsockets-2.1-stable/ssl-client.d \
./src/app/libwebsockets-2.1-stable/ssl.d 


# Each subdirectory must supply rules for building sources it contributes
src/app/libwebsockets-2.1-stable/base64-decode.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/base64-decode.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/client-handshake.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/client-handshake.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/client-parser.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/client-parser.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/client.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/client.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/context.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/context.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/handshake.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/handshake.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/header.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/header.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/libwebsockets.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/libwebsockets.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/lws-plat-wm.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/lws-plat-wm.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/output.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/output.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/parsers.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/parsers.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/pollfd.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/pollfd.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/service.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/service.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/ssl-client.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/ssl-client.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
src/app/libwebsockets-2.1-stable/ssl.o: D:/work-document/Seafile/20200606/1_SDK/wm_sdk_w800_20200605/src/app/libwebsockets-2.1-stable/ssl.c
	@echo 'Building file: $<'
	@csky-elfabiv2-gcc -mcpu=ck804ef -DGCC_COMPILE=1 -DTLS_CONFIG_CPU_XT804=1 -I../../../../../../../demo -I../../../../../../../include -I../../../../../../../include/arch/xt804 -I../../../../../../../include/arch/xt804/csi_core -I../../../../../../../include/app -I../../../../../../../include/driver -I../../../../../../../include/net -I../../../../../../../include/os -I../../../../../../../include/platform -I../../../../../../../include/wifi -I../../../../../../../include/bt -I../../../../../../../platform/arch/xt804/bsp/include -I../../../../../../../platform/common/crypto -I../../../../../../../platform/common/params -I../../../../../../../platform/common/crypto/digest -I../../../../../../../platform/common/crypto/keyformat -I../../../../../../../platform/common/crypto/math -I../../../../../../../platform/common/crypto/prng -I../../../../../../../platform/common/crypto/pubkey -I../../../../../../../platform/common/crypto/symmetric -I../../../../../../../platform/inc -I../../../../../../../src/app/dhcpserver -I../../../../../../../src/app/dnsserver -I../../../../../../../src/app/ping -I../../../../../../../src/app/iperf -I../../../../../../../src/app/wm_atcmd -I../../../../../../../src/app/httpclient -I../../../../../../../src/app/ota -I../../../../../../../src/app/matrixssl -I../../../../../../../src/app/polarssl/include -I../../../../../../../src/app/libwebsockets-2.1-stable -I../../../../../../../src/app/mDNS/mDNSCore -I../../../../../../../src/app/mDNS/mDNSPosix -I../../../../../../../src/app/mqtt -I../../../../../../../src/network/lwip2.0.3/include -I../../../../../../../src/network/api2.0.3 -I../../../../../../../src/os/rtos/include -O2 -fdata-sections -mhard-float -g3 -Wall -c -ffunction-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"

